// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: 'API_ID',
    messagingSenderId: 'MSG_SENDER',
    projectId: 'ir-login-xxxx',
    authDomain: 'ir-login-xxxx.firebaseapp.com',
    storageBucket: 'ir-login-xxxx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'APIkey',
    appId: 'appID',
    messagingSenderId: 'SenderId',
    projectId: 'ir-login-XXXX',
    storageBucket: 'ir-login-XXXX.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'APIkey',
    appId: 'appID',
    messagingSenderId: 'sender_id',
    projectId: 'ir-login-xxxx',
    storageBucket: 'ir-login-xxxx.appspot.com',
    androidClientId: 'clientId',
    iosClientId: 'iosClientId',
    iosBundleId: 'iosBundleId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'apiKey',
    appId: 'appId',
    messagingSenderId: 'SenderId',
    projectId: 'ir-login-xxxx',
    storageBucket: 'ir-login-xxxx.appspot.com',
    androidClientId: 'ClientId',
    iosClientId: 'ClientId',
    iosBundleId: 'BundleId',
  );
}
