// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxJ2j9T4lS6TxC9h5a72PdZPY8Dbeqs-M',
    appId: '1:563586671233:web:cfc67fb64b178958db2380',
    messagingSenderId: '563586671233',
    projectId: 'ir-login-6fb82',
    authDomain: 'ir-login-6fb82.firebaseapp.com',
    storageBucket: 'ir-login-6fb82.appspot.com',
    measurementId: 'G-0EGX1MK0PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA090Ip6K9ZEA5pMcMWbeUNRNem5yFAmg',
    appId: '1:563586671233:android:36e2adf9f91b7ae4db2380',
    messagingSenderId: '563586671233',
    projectId: 'ir-login-6fb82',
    storageBucket: 'ir-login-6fb82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-1q9TBHwO-VXcoYlPdzdsWipdU0LSc6Q',
    appId: '1:563586671233:ios:fd34e7d44100a85bdb2380',
    messagingSenderId: '563586671233',
    projectId: 'ir-login-6fb82',
    storageBucket: 'ir-login-6fb82.appspot.com',
    androidClientId: '563586671233-uut37sa5vp4j944k8li9tfpcasmui0kb.apps.googleusercontent.com',
    iosClientId: '563586671233-kl05a2lbr6i7dhch33uvtoiag6ihcadk.apps.googleusercontent.com',
    iosBundleId: 'com.example.irSimulation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-1q9TBHwO-VXcoYlPdzdsWipdU0LSc6Q',
    appId: '1:563586671233:ios:1b809984d96b6925db2380',
    messagingSenderId: '563586671233',
    projectId: 'ir-login-6fb82',
    storageBucket: 'ir-login-6fb82.appspot.com',
    androidClientId: '563586671233-uut37sa5vp4j944k8li9tfpcasmui0kb.apps.googleusercontent.com',
    iosClientId: '563586671233-mmrcs8534kfn9smecs4bv0qjo9egssof.apps.googleusercontent.com',
    iosBundleId: 'com.example.irSimulation.RunnerTests',
  );
}
