// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUdNEgfxEGkPh6bEIIfimVPUSxRhd2v54',
    appId: '1:593031519447:web:4c68d7427a5b4c8aa8e492',
    messagingSenderId: '593031519447',
    projectId: 'ir-login-6f28c',
    authDomain: 'ir-login-6f28c.firebaseapp.com',
    storageBucket: 'ir-login-6f28c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaciK3oO5Hly21arY7Ti_j06Ko3ypT9bM',
    appId: '1:593031519447:android:a499e9e76bed0247a8e492',
    messagingSenderId: '593031519447',
    projectId: 'ir-login-6f28c',
    storageBucket: 'ir-login-6f28c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLwl0w40Hbhp7wAtW2z1so6Yc3CPMiEiI',
    appId: '1:593031519447:ios:c07eb2b6204eca79a8e492',
    messagingSenderId: '593031519447',
    projectId: 'ir-login-6f28c',
    storageBucket: 'ir-login-6f28c.appspot.com',
    androidClientId: '593031519447-o1q8sfo5o0c2b6hj9tga88rf50uoohg4.apps.googleusercontent.com',
    iosClientId: '593031519447-j1v2k52b5r551ot8outpotua9votc53a.apps.googleusercontent.com',
    iosBundleId: 'com.example.irSimulation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLwl0w40Hbhp7wAtW2z1so6Yc3CPMiEiI',
    appId: '1:593031519447:ios:9510b024cb47b858a8e492',
    messagingSenderId: '593031519447',
    projectId: 'ir-login-6f28c',
    storageBucket: 'ir-login-6f28c.appspot.com',
    androidClientId: '593031519447-o1q8sfo5o0c2b6hj9tga88rf50uoohg4.apps.googleusercontent.com',
    iosClientId: '593031519447-2vghhlmv93874s223uj5970k7r6nvmap.apps.googleusercontent.com',
    iosBundleId: 'com.example.irSimulation.RunnerTests',
  );
}
